/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package perpusdigital;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hilman
 */
public class kelbuku2 extends javax.swing.JPanel {
    public final void loadData() {
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MySQL://localhost:3306/db_perpus";
        SUser = "root";
        SPass = "";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();
            DefaultTableModel model = new DefaultTableModel(new String[]{"ID Buku", "Judul Buku", "Pengarang", "Penerbit", "Tahun Terbit"}, 0);
            tabelbuku.setModel(model);
            String sql = "SELECT * FROM buku";
            java.sql.ResultSet rs = st.executeQuery(sql);
            String idBuku, judulBuku, pengarang, penerbit, tahunTerbit;
            while (rs.next()) {
                idBuku = rs.getString("id_buku");
                judulBuku = rs.getString("judul_buku");
                pengarang = rs.getString("pengarang");
                penerbit = rs.getString("penerbit");
                tahunTerbit = rs.getString("tahun_terbit");
                model.addRow(new Object[]{idBuku, judulBuku, pengarang, penerbit, tahunTerbit});
            }
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
    }
    /**
     * Creates new form kelbuku2
     */
    public kelbuku2() {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelmain = new javax.swing.JPanel();
        panelview = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelbuku = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        paneladd = new javax.swing.JPanel();
        addBuku = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        idBuku = new javax.swing.JTextField();
        judulBuku = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pengarang = new javax.swing.JTextField();
        penerbit = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        thnTerbit = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelbuku = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        panelmain.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Kelola Buku");

        tabelbuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Buku", "Judul Buku", "Pengarang", "Penerbit", "Tahun Terbit"
            }
        ));
        tabelbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelbuku);

        txtCari.setPreferredSize(new java.awt.Dimension(64, 30));
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.setPreferredSize(new java.awt.Dimension(72, 30));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hilman\\Documents\\Downloads\\java\\icons8-book-20.png")); // NOI18N

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Master > Kelola Buku");

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hilman\\Documents\\Downloads\\java\\icons8-tv-20.png")); // NOI18N

        javax.swing.GroupLayout panelviewLayout = new javax.swing.GroupLayout(panelview);
        panelview.setLayout(panelviewLayout);
        panelviewLayout.setHorizontalGroup(
            panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelviewLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelviewLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE)
                    .addGroup(panelviewLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        panelviewLayout.setVerticalGroup(
            panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelviewLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );

        panelmain.add(panelview, "card2");

        addBuku.setBackground(new java.awt.Color(128, 0, 0));
        addBuku.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        addBuku.setForeground(new java.awt.Color(255, 255, 255));
        addBuku.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hilman\\Documents\\Downloads\\java\\icons8-save-15.png")); // NOI18N
        addBuku.setText("SIMPAN");
        addBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBukuActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Buku");

        jLabel5.setText("Judul Buku");

        jLabel6.setText("Pengarang");

        jLabel7.setText("Penerbit");

        jLabel8.setText("Tahun Terbit");

        jButton5.setBackground(new java.awt.Color(128, 0, 0));
        jButton5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hilman\\Documents\\Downloads\\java\\icons8-cancel-15.png")); // NOI18N
        jButton5.setText("BATAL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Master > Kelola Buku");

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hilman\\Documents\\Downloads\\java\\icons8-tv-20.png")); // NOI18N

        labelbuku.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        labelbuku.setForeground(new java.awt.Color(51, 51, 51));
        labelbuku.setText("Tambah Buku");

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hilman\\Documents\\Downloads\\java\\icons8-book-20.png")); // NOI18N

        javax.swing.GroupLayout paneladdLayout = new javax.swing.GroupLayout(paneladd);
        paneladd.setLayout(paneladdLayout);
        paneladdLayout.setHorizontalGroup(
            paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneladdLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(judulBuku)
                    .addComponent(idBuku)
                    .addGroup(paneladdLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelbuku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 681, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11))
                    .addComponent(pengarang)
                    .addGroup(paneladdLayout.createSequentialGroup()
                        .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(paneladdLayout.createSequentialGroup()
                                .addComponent(addBuku)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(penerbit)
                    .addComponent(thnTerbit))
                .addGap(20, 20, 20))
        );
        paneladdLayout.setVerticalGroup(
            paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneladdLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel14)
                        .addComponent(labelbuku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(judulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thnTerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBuku)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        panelmain.add(paneladd, "card2");

        add(panelmain, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void tabelbukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbukuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelbukuMouseClicked

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        cariData();
    }//GEN-LAST:event_btnCariActionPerformed

    private void addBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBukuActionPerformed
        // TODO add your handling code here:

        if (addBuku.getText().equals("TAMBAH")) {
            addBuku.setText("SIMPAN");
        } else if (addBuku.getText().equals("SIMPAN")) {
            tambahdata();
        } else if (addBuku.getText().equals("PERBARUI")) {
            updateData();
        }
    }//GEN-LAST:event_addBukuActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        panelmain.removeAll();
        panelmain.add(panelview);
        panelmain.repaint();
        panelmain.revalidate();
    }//GEN-LAST:event_jButton5ActionPerformed

    
    private void showPanel() {
        panelmain.removeAll();
        panelmain.add(new kelbuku());
        panelmain.repaint();
        panelmain.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBuku;
    private javax.swing.JButton btnCari;
    private javax.swing.JTextField idBuku;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField judulBuku;
    private javax.swing.JLabel labelbuku;
    private javax.swing.JPanel paneladd;
    private javax.swing.JPanel panelmain;
    private javax.swing.JPanel panelview;
    private javax.swing.JTextField penerbit;
    private javax.swing.JTextField pengarang;
    private javax.swing.JTable tabelbuku;
    private javax.swing.JTextField thnTerbit;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
private void tambahdata() {
        String dbUrl = "jdbc:mysql://localhost:3306/db_perpus";
        String dbUser = "root";
        String dbPass = "";

        String sql = "INSERT INTO buku (id_buku, judul_buku, pengarang, penerbit, tahun_terbit) VALUES (?, ?, ?, ?, ?)";

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection(dbUrl, dbUser, dbPass);

            if ("".equals(idBuku.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "ID Buku harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else if ("".equals(judulBuku.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Judul Buku harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else if ("".equals(pengarang.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Pengarang harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else if ("".equals(penerbit.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Penerbit harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else if ("".equals(thnTerbit.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Tahun Terbit harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else {
                try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                    stmt.setString(1, idBuku.getText());
                    stmt.setString(2, judulBuku.getText());
                    stmt.setString(3, pengarang.getText());
                    stmt.setString(4, penerbit.getText());
                    stmt.setString(5, thnTerbit.getText());

                    stmt.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
                    idBuku.setText("");
                    judulBuku.setText("");
                    pengarang.setText("");
                    penerbit.setText("");
                    thnTerbit.setText("");
                    showPanel();
                    loadData();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
                } finally {
                    conn.close();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), "Error! " + e.getMessage());
        }
    }

    private void dataTabel() {
        panelview.setVisible(false);
        paneladd.setVisible(true);

        int row = tabelbuku.getSelectedRow();
        labelbuku.setText("Perbarui Data Buku Perpustakaan");

        idBuku.setEnabled(false);

        idBuku.setText(tabelbuku.getValueAt(row, 0).toString());
        judulBuku.setText(tabelbuku.getValueAt(row, 1).toString());
        pengarang.setText(tabelbuku.getValueAt(row, 2).toString());
        penerbit.setText(tabelbuku.getValueAt(row, 3).toString());
        thnTerbit.setText(tabelbuku.getValueAt(row, 4).toString());
    }

    private void updateData() {
        String dbUrl = "jdbc:mysql://localhost:3306/db_perpus";
        String dbUser = "root";
        String dbPass = "";

        String sql = "UPDATE  buku SET judul_buku=?, pengarang=?, penerbit=?, tahun_terbit=? WHERE id_buku=?";

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection(dbUrl, dbUser, dbPass);

            if ("".equals(idBuku.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "ID Buku harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else if ("".equals(judulBuku.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Judul Buku harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else if ("".equals(pengarang.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Pengarang harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else if ("".equals(penerbit.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Penerbit harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else if ("".equals(thnTerbit.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Tahun Terbit harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else {
                try (PreparedStatement stmt = conn.prepareStatement(sql)) {

                    stmt.setString(1, judulBuku.getText());
                    stmt.setString(2, pengarang.getText());
                    stmt.setString(3, penerbit.getText());
                    stmt.setString(4, thnTerbit.getText());
                    stmt.setString(5, idBuku.getText());

                    stmt.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
                    idBuku.setText("");
                    judulBuku.setText("");
                    pengarang.setText("");
                    penerbit.setText("");
                    thnTerbit.setText("");
                    showPanel();
                    loadData();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
                } finally {
                    conn.close();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), "Error! " + e.getMessage());
        }

    }

    private void hapusData() {
        int selectedRow = tabelbuku.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang akan dihapus", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah yakin ingin menghapus data?",
                "Konfirmasi Hapus Data", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String idBuku = (String) tabelbuku.getValueAt(selectedRow, 0);
            String dbUrl = "jdbc:mysql://localhost:3306/db_perpus";
            String dbUser = "root";
            String dbPass = "";

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection(dbUrl, dbUser, dbPass);
                String sql = "DELETE FROM buku WHERE id_buku = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, idBuku);
                int rowsAffected = pst.executeUpdate();
                if (rowsAffected > 0) {
                    ((DefaultTableModel) tabelbuku.getModel()).removeRow(selectedRow);
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data", "Error", JOptionPane.ERROR_MESSAGE);
                }
                pst.close();
                con.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void cariData() {
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MySQL://localhost:3306/db_perpus";
        SUser = "root";
        SPass = "";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();
            DefaultTableModel model = new DefaultTableModel(new String[]{"ID Buku", "Judul Buku", "Pengarang", "Penerbit", "Tahun Terbit"}, 0);
            tabelbuku.setModel(model);

            String searchKeyword = txtCari.getText();
            String sql = "SELECT * FROM buku WHERE judul_buku LIKE '" + searchKeyword + "%'";
            java.sql.ResultSet rs = st.executeQuery(sql);

            String idBuku, judulBuku, pengarang, penerbit, tahunTerbit;
            while (rs.next()) {
                idBuku = rs.getString("id_buku");
                judulBuku = rs.getString("judul_buku");
                pengarang = rs.getString("pengarang");
                penerbit = rs.getString("penerbit");
                tahunTerbit = rs.getString("tahun_terbit");
                model.addRow(new Object[]{idBuku, judulBuku, pengarang, penerbit, tahunTerbit});
            }
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }

    }

}
