/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package perpusdigital;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hilman
 */
public class kelolakunjungan2 extends javax.swing.JPanel {
    public final void loadData() {
        String SUrl = "jdbc:MySQL://localhost:3306/db_perpus";
        String SUser = "root";
        String SPass = "";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();
            DefaultTableModel model = new DefaultTableModel(new String[]{"Nama", "Prodi/Dosen", "NIM/NIDN", "Tujuan", "Tanggal", "Tingkat"}, 0);
            tabelkunjungan.setModel(model);
            String sql = "SELECT * FROM kunjungan";
            java.sql.ResultSet rs = st.executeQuery(sql);
            String nama, prodi, nim, tujuan, tanggal, tingkat;
            while (rs.next()) {
                nama = rs.getString("nama");
                prodi = rs.getString("prodi");
                nim = rs.getString("nim");
                tujuan = rs.getString("tujuan");
                tanggal = rs.getString("tanggal");
                tingkat = rs.getString("tingkat");
                model.addRow(new Object[]{nama, prodi, nim, tujuan, tanggal, tingkat});
            }
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
    }
    /**
     * Creates new form kelolakunjungan2
     */
    public kelolakunjungan2() {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelmain = new javax.swing.JPanel();
        panelview = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelkunjungan = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        paneladd = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nim = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tingkat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        labelkunjungan = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        addkunjungan = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        prodi = new javax.swing.JComboBox<>();
        tujuan = new javax.swing.JComboBox<>();
        tanggal = new com.toedter.calendar.JDateChooser();

        setLayout(new java.awt.CardLayout());

        panelmain.setLayout(new java.awt.CardLayout());

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Data Kunjungan");

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hilman\\Documents\\Downloads\\java\\icons8-time-20.png")); // NOI18N

        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hilman\\Documents\\Downloads\\java\\icons8-tv-20.png")); // NOI18N

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Master > Data Kunjungan");

        txtCari.setPreferredSize(new java.awt.Dimension(64, 30));
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.setPreferredSize(new java.awt.Dimension(72, 30));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        tabelkunjungan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "Prodi/Dosen", "NIM/NIDN", "Tujuan", "Tanggal", "Tingkat"
            }
        ));
        tabelkunjungan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelkunjunganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelkunjungan);

        btnAdd.setBackground(new java.awt.Color(0, 153, 51));
        btnAdd.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hilman\\Documents\\Downloads\\java\\icons8-add-15.png")); // NOI18N
        btnAdd.setText("TAMBAH");
        btnAdd.setPreferredSize(new java.awt.Dimension(113, 30));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelviewLayout = new javax.swing.GroupLayout(panelview);
        panelview.setLayout(panelviewLayout);
        panelviewLayout.setHorizontalGroup(
            panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelviewLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelviewLayout.createSequentialGroup()
                        .addGroup(panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelviewLayout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1014, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(panelviewLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addGap(20, 20, 20))))
        );
        panelviewLayout.setVerticalGroup(
            panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelviewLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel16)
                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        panelmain.add(panelview, "card2");

        jLabel1.setText("Nama Lengkap");

        jLabel5.setText("Prodi/Dosen");

        jLabel6.setText("NIM/NIDN");

        jLabel7.setText("Tujuan Kunjungan");

        jLabel8.setText("Tanggal");

        jLabel9.setText("Tingkat");

        labelkunjungan.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        labelkunjungan.setForeground(new java.awt.Color(51, 51, 51));
        labelkunjungan.setText("Tambah Kunjungan");

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hilman\\Documents\\Downloads\\java\\icons8-time-20.png")); // NOI18N

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hilman\\Documents\\Downloads\\java\\icons8-tv-20.png")); // NOI18N

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Master > Data Kunjungan");

        addkunjungan.setBackground(new java.awt.Color(128, 0, 0));
        addkunjungan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        addkunjungan.setForeground(new java.awt.Color(255, 255, 255));
        addkunjungan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hilman\\Documents\\Downloads\\java\\icons8-save-15.png")); // NOI18N
        addkunjungan.setText("SIMPAN");
        addkunjungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addkunjunganActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(128, 0, 0));
        jButton5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hilman\\Documents\\Downloads\\java\\icons8-cancel-15.png")); // NOI18N
        jButton5.setText("BATAL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        prodi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S1 Keperawatan", "D3 Keperawatan", "D3 Kebidanan", "S1 Keperawatan non reguler", "Profesi Ners", "S1 Informatika", "S1 Sisitem Informasi", "D3 Sistem Informasi", "S1 Akuntansi", "S1 Manajenem", "SOG", "DOSIS" }));
        prodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodiActionPerformed(evt);
            }
        });

        tujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Membaca", "Meminjam Buku", "Mengembalikan Buku", "Mengerjakan Tugas/Skripsi", "Mengumpulkan Skripsi/Magang/Karya Ilmia", "Diskusi/Kerja Kelompok", " " }));

        javax.swing.GroupLayout paneladdLayout = new javax.swing.GroupLayout(paneladd);
        paneladd.setLayout(paneladdLayout);
        paneladdLayout.setHorizontalGroup(
            paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneladdLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneladdLayout.createSequentialGroup()
                        .addComponent(addkunjungan)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneladdLayout.createSequentialGroup()
                        .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tanggal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tujuan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prodi, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneladdLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelkunjungan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 605, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11))
                            .addComponent(nim, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paneladdLayout.createSequentialGroup()
                                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tingkat, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(20, 20, 20))))
        );
        paneladdLayout.setVerticalGroup(
            paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneladdLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel14)
                        .addComponent(labelkunjungan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tingkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addkunjungan)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        panelmain.add(paneladd, "card2");

        add(panelmain, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        cariData();
    }//GEN-LAST:event_btnCariActionPerformed

    private void tabelkunjunganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelkunjunganMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelkunjunganMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        panelmain.removeAll();
        panelmain.add(paneladd);
        panelmain.repaint();
        panelmain.revalidate();

        if (btnAdd.getText().equals("UBAH")) {
            dataTabel();
            addkunjungan.setText("PERBARUI");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void addkunjunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addkunjunganActionPerformed
        // TODO add your handling code here:
        if (addkunjungan.getText().equals("TAMBAH")) {
            addkunjungan.setText("SIMPAN");
        } else if (addkunjungan.getText().equals("SIMPAN")) {
            tambahdata();
        } else if (addkunjungan.getText().equals("PERBARUI")) {
            updateData();
        }
    }//GEN-LAST:event_addkunjunganActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        panelmain.removeAll();
        panelmain.add(panelview);
        panelmain.repaint();
        panelmain.revalidate();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void prodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodiActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_prodiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addkunjungan;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelkunjungan;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nim;
    private javax.swing.JPanel paneladd;
    private javax.swing.JPanel panelmain;
    private javax.swing.JPanel panelview;
    private javax.swing.JComboBox<String> prodi;
    private javax.swing.JTable tabelkunjungan;
    private com.toedter.calendar.JDateChooser tanggal;
    private javax.swing.JTextField tingkat;
    private javax.swing.JComboBox<String> tujuan;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables

    private void showPanel() {
        panelmain.removeAll();
        panelmain.add(new kelolakunjungan());
        panelmain.repaint();
        panelmain.revalidate();
    }

    private void tambahdata() {
        String dbUrl = "jdbc:mysql://localhost:3306/db_perpus";
        String dbUser = "root";
        String dbPass = "";

        String sqlInsert = "INSERT INTO kunjungan (nama, prodi, nim, tujuan, tanggal, tingkat) VALUES (?, ?, ?, ?, ?, ?)";
        String sqlUpdate = "UPDATE kunjungan SET nama = ?, prodi = ?, tujuan = ?, tanggal = ?, tingkat = ? WHERE nim = ?";

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection(dbUrl, dbUser, dbPass);

            // Check if fields are empty
            if (nama.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(new JFrame(), "Nama harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else if (prodi.getSelectedItem() == null || prodi.getSelectedItem().toString().trim().isEmpty()) {
                JOptionPane.showMessageDialog(new JFrame(), "Prodi harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else if (nim.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(new JFrame(), "NIM harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else if (tujuan.getSelectedItem() == null || tujuan.getSelectedItem().toString().trim().isEmpty()) {
                JOptionPane.showMessageDialog(new JFrame(), "Tujuan harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else if (tanggal.getDate() == null) {
                JOptionPane.showMessageDialog(new JFrame(), "Tanggal harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else if (tingkat.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(new JFrame(), "Tingkat harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else {
                String sql = addkunjungan.getText().equals("PERBARUI") ? sqlUpdate : sqlInsert;

                try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                    stmt.setString(1, nama.getText());
                    stmt.setString(2, prodi.getSelectedItem().toString());
                    stmt.setString(3, nim.getText());
                    stmt.setString(4, tujuan.getSelectedItem().toString());
                    stmt.setDate(5, new java.sql.Date(tanggal.getDate().getTime())); // Convert to java.sql.Date
                    stmt.setString(6, tingkat.getText());

                    if (addkunjungan.getText().equals("PERBARUI")) {
                        stmt.setString(7, nim.getText()); // Set NIM for WHERE clause
                    }

                    stmt.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
                    nama.setText("");
                    prodi.setSelectedIndex(-1);
                    nim.setText("");
                    tujuan.setSelectedIndex(-1);
                    tanggal.setDate(null);
                    tingkat.setText("");
                    showPanel();
                    loadData();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
                } finally {
                    conn.close();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), "Error! " + e.getMessage());
        }
    }

    private void dataTabel() {
        panelview.setVisible(false);
        paneladd.setVisible(true);

        int row = tabelkunjungan.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row first.");
            return;
        }

        labelkunjungan.setText("Perbarui Data Buku Perpustakaan");

        nim.setEnabled(false);

        // Fetch and set the values from the table to the form fields
        try {
            String namaVal = tabelkunjungan.getValueAt(row, 0).toString();
            String prodiVal = tabelkunjungan.getValueAt(row, 1).toString();
            String nimVal = tabelkunjungan.getValueAt(row, 2).toString();
            String tujuanVal = tabelkunjungan.getValueAt(row, 3).toString();
            String tanggalVal = tabelkunjungan.getValueAt(row, 4).toString();
            String tingkatVal = tabelkunjungan.getValueAt(row, 5).toString();

            // Set the values to the form fields
            nama.setText(namaVal);
            prodi.setSelectedItem(prodiVal);
            nim.setText(nimVal);
            tujuan.setSelectedItem(tujuanVal);

            // Convert string to date and set it to the date picker
            java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(tanggalVal);
            tanggal.setDate(date);

            tingkat.setText(tingkatVal);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error setting data: " + e.getMessage());
        }
    }

    private void updateData() {
        String dbUrl = "jdbc:mysql://localhost:3306/db_perpus";
        String dbUser = "root";
        String dbPass = "";

        String sql = "UPDATE kunjungan SET nama=?, prodi=?, tujuan=?, tanggal=?, tingkat=? WHERE nim=?";

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection(dbUrl, dbUser, dbPass);

            // Validate form fields
            if (nama.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(new JFrame(), "Nama harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else if (prodi.getSelectedItem() == null || prodi.getSelectedItem().toString().trim().isEmpty()) {
                JOptionPane.showMessageDialog(new JFrame(), "Prodi harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else if (nim.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(new JFrame(), "NIM harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else if (tujuan.getSelectedItem() == null || tujuan.getSelectedItem().toString().trim().isEmpty()) {
                JOptionPane.showMessageDialog(new JFrame(), "Tujuan harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else if (tanggal.getDate() == null) {
                JOptionPane.showMessageDialog(new JFrame(), "Tanggal harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else if (tingkat.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(new JFrame(), "Tingkat harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else {
                // Update the database record
                try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                    stmt.setString(1, nama.getText());
                    stmt.setString(2, prodi.getSelectedItem().toString());
                    stmt.setString(3, tujuan.getSelectedItem().toString());
                    stmt.setDate(4, new java.sql.Date(tanggal.getDate().getTime())); // Convert to java.sql.Date
                    stmt.setString(5, tingkat.getText());
                    stmt.setString(6, nim.getText());

                    stmt.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");

                    // Reset form fields after successful update
                    nama.setText("");
                    prodi.setSelectedIndex(-1);
                    nim.setText("");
                    tujuan.setSelectedIndex(-1);
                    tanggal.setDate(null);
                    tingkat.setText("");
                    showPanel();
                    loadData();  // Reload the table data to reflect the updates
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
                } finally {
                    conn.close();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), "Error! " + e.getMessage());
        }
    }

    private void hapusData() {
        int selectedRow = tabelkunjungan.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang akan dihapus", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah yakin ingin menghapus data?",
                "Konfirmasi Hapus Data", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String nama = (String) tabelkunjungan.getValueAt(selectedRow, 0);
            String dbUrl = "jdbc:mysql://localhost:3306/db_perpus";
            String dbUser = "root";
            String dbPass = "";

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection(dbUrl, dbUser, dbPass);
                String sql = "DELETE FROM kunjungan WHERE nama = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, nama);
                int rowsAffected = pst.executeUpdate();
                if (rowsAffected > 0) {
                    ((DefaultTableModel) tabelkunjungan.getModel()).removeRow(selectedRow);
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data", "Error", JOptionPane.ERROR_MESSAGE);
                }
                pst.close();
                con.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void cariData() {
        String SUrl = "jdbc:mysql://localhost:3306/db_perpus";
        String SUser = "root";
        String SPass = "";

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            DefaultTableModel model = new DefaultTableModel(new String[]{"Nama", "Prodi/Dosen", "NIM/NIDN", "Tujuan", "Tanggal", "Tingkat"}, 0);
            tabelkunjungan.setModel(model);

            String searchKeyword = txtCari.getText();
            String sql = "SELECT * FROM kunjungan WHERE nama LIKE ?";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, "%" + searchKeyword + "%");

            java.sql.ResultSet rs = stmt.executeQuery();

            String nama, prodi, nim, tujuan, tanggal, tingkat;
            while (rs.next()) {
                nama = rs.getString("nama");
                prodi = rs.getString("prodi");
                nim = rs.getString("nim");
                tujuan = rs.getString("tujuan");
                tanggal = rs.getString("tanggal");
                tingkat = rs.getString("tingkat");
                model.addRow(new Object[]{nama, prodi, nim, tujuan, tanggal, tingkat});
            }
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
    }

}
