/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package perpusdigital;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hilman
 */
public class kelolapegawai extends javax.swing.JPanel {
    public final void loadData() {
        btnHapus.setVisible(false);
        btnCancel.setVisible(false);
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MySQL://localhost:3306/db_perpus";
        SUser = "root";
        SPass = "";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();
            DefaultTableModel model = new DefaultTableModel(new String[]{"NIDN", "Nama Lengkap", "Email", "Divisi"}, 0);
            tabelpegawai.setModel(model);
            String sql = "SELECT * FROM pegawai";
            java.sql.ResultSet rs = st.executeQuery(sql);
            String nidn,nama,email,divisi;
            while (rs.next()) {
                nidn = rs.getString("nidn");
                nama = rs.getString("nama");
                email = rs.getString("email");
                divisi = rs.getString("divisi");
                model.addRow(new Object[]{nidn, nama, email, divisi});
            }
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
    }
    /**
     * Creates new form contoh
     */
    public kelolapegawai() {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelmain = new javax.swing.JPanel();
        panelview = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelpegawai = new javax.swing.JTable();
        btnCancel = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        paneladd = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nidn = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        divisi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        labelpegawai = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        addPegawai = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        panelmain.setLayout(new java.awt.CardLayout());

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Data Pegawai");

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hilman\\Documents\\Downloads\\java\\icons8-users-20.png")); // NOI18N

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Master > Data Pegawai");

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hilman\\Documents\\Downloads\\java\\icons8-tv-20.png")); // NOI18N

        txtCari.setPreferredSize(new java.awt.Dimension(64, 30));
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.setPreferredSize(new java.awt.Dimension(72, 30));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        tabelpegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIDN", "Nama Lengkap", "Email", "Divisi"
            }
        ));
        tabelpegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelpegawaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelpegawai);

        btnCancel.setBackground(new java.awt.Color(0, 153, 255));
        btnCancel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hilman\\Documents\\Downloads\\java\\icons8-add-15.png")); // NOI18N
        btnCancel.setText("BATAL");
        btnCancel.setPreferredSize(new java.awt.Dimension(113, 30));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(128, 0, 0));
        btnHapus.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hilman\\Documents\\Downloads\\java\\icons8-add-15.png")); // NOI18N
        btnHapus.setText("HAPUS");
        btnHapus.setPreferredSize(new java.awt.Dimension(113, 30));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(0, 153, 51));
        btnAdd.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hilman\\Documents\\Downloads\\java\\icons8-add-15.png")); // NOI18N
        btnAdd.setText("TAMBAH");
        btnAdd.setPreferredSize(new java.awt.Dimension(113, 30));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelviewLayout = new javax.swing.GroupLayout(panelview);
        panelview.setLayout(panelviewLayout);
        panelviewLayout.setHorizontalGroup(
            panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelviewLayout.createSequentialGroup()
                .addGroup(panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelviewLayout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addGroup(panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelviewLayout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1014, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelviewLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)))
                .addGap(20, 20, 20))
        );
        panelviewLayout.setVerticalGroup(
            panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelviewLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel14)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                    .addGroup(panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );

        panelmain.add(panelview, "card2");

        jLabel1.setText("NIDN");

        jLabel5.setText("Nama Lengkap");

        jLabel6.setText("Email");

        jLabel7.setText("Divisi");

        labelpegawai.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        labelpegawai.setForeground(new java.awt.Color(51, 51, 51));
        labelpegawai.setText("Tambah Pegawai");

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hilman\\Documents\\Downloads\\java\\icons8-users-20.png")); // NOI18N

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Master > Data Pegawai");

        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hilman\\Documents\\Downloads\\java\\icons8-tv-20.png")); // NOI18N

        addPegawai.setBackground(new java.awt.Color(128, 0, 0));
        addPegawai.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        addPegawai.setForeground(new java.awt.Color(255, 255, 255));
        addPegawai.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hilman\\Documents\\Downloads\\java\\icons8-save-15.png")); // NOI18N
        addPegawai.setText("SIMPAN");
        addPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPegawaiActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(128, 0, 0));
        jButton5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hilman\\Documents\\Downloads\\java\\icons8-cancel-15.png")); // NOI18N
        jButton5.setText("BATAL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneladdLayout = new javax.swing.GroupLayout(paneladd);
        paneladd.setLayout(paneladdLayout);
        paneladdLayout.setHorizontalGroup(
            paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneladdLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneladdLayout.createSequentialGroup()
                        .addComponent(addPegawai)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(paneladdLayout.createSequentialGroup()
                        .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama)
                            .addComponent(nidn)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneladdLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelpegawai)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 643, Short.MAX_VALUE)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17))
                            .addComponent(email)
                            .addGroup(paneladdLayout.createSequentialGroup()
                                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(divisi))
                        .addGap(20, 20, 20))))
        );
        paneladdLayout.setVerticalGroup(
            paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneladdLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel16)
                        .addComponent(labelpegawai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel18)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nidn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(divisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPegawai)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(266, Short.MAX_VALUE))
        );

        panelmain.add(paneladd, "card2");

        add(panelmain, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void addPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPegawaiActionPerformed
        // TODO add your handling code here:
        if (addPegawai.getText().equals("TAMBAH")) {
            addPegawai.setText("SIMPAN");
        } else if (addPegawai.getText().equals("SIMPAN")) {
            tambahdata();
        } else if (addPegawai.getText().equals("PERBARUI")) {
            updateData();
        }
    }//GEN-LAST:event_addPegawaiActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        panelmain.removeAll();
        panelmain.add(panelview);
        panelmain.repaint();
        panelmain.revalidate();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        showPanel();
        loadData();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        hapusData();
        showPanel();
        loadData();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        panelmain.removeAll();
        panelmain.add(paneladd);
        panelmain.repaint();
        panelmain.revalidate();

        if (btnAdd.getText().equals("UBAH")) {
            dataTabel();
            addPegawai.setText("PERBARUI");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        cariData();
    }//GEN-LAST:event_btnCariActionPerformed

    private void tabelpegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelpegawaiMouseClicked
        // TODO add your handling code here:
        if (btnAdd.getText().equals("TAMBAH")) {
            btnAdd.setText("UBAH");
            btnHapus.setVisible(true);
            btnCancel.setVisible(true);
        }
    }//GEN-LAST:event_tabelpegawaiMouseClicked

     private void showPanel() {
        panelmain.removeAll();
        panelmain.add(new kelolapegawai());
        panelmain.repaint();
        panelmain.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPegawai;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JTextField divisi;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelpegawai;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nidn;
    private javax.swing.JPanel paneladd;
    private javax.swing.JPanel panelmain;
    private javax.swing.JPanel panelview;
    private javax.swing.JTable tabelpegawai;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    
    
    private void tambahdata() {
        String dbUrl = "jdbc:mysql://localhost:3306/db_perpus";
        String dbUser = "root";
        String dbPass = "";

        String sql = "INSERT INTO pegawai (nidn, nama, email, divisi) VALUES (?, ?, ?, ?)";

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection(dbUrl, dbUser, dbPass);

            if ("".equals(nidn.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "NIDN harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else if ("".equals(nama.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Nama harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else if ("".equals(email.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Email harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else if ("".equals(divisi.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Divisi harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } 
            else {
                try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                    stmt.setString(1, nidn.getText());
                    stmt.setString(2, nama.getText());
                    stmt.setString(3, email.getText());
                    stmt.setString(4, divisi.getText());

                    stmt.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
                    nidn.setText("");
                    nama.setText("");
                    email.setText("");
                    divisi.setText("");
                    showPanel();
                    loadData();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
                } finally {
                    conn.close();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), "Error! " + e.getMessage());
        }
    }

    private void dataTabel() {
        panelview.setVisible(false);
        paneladd.setVisible(true);

        int row = tabelpegawai.getSelectedRow();
        labelpegawai.setText("Perbarui Pegawai Perpustakaan");
        
        nidn.setEnabled(false);

        nidn.setText(tabelpegawai.getValueAt(row, 0).toString());
        nama.setText(tabelpegawai.getValueAt(row, 1).toString());
        email.setText(tabelpegawai.getValueAt(row, 2).toString());
        divisi.setText(tabelpegawai.getValueAt(row, 3).toString());
    }

    private void updateData() {
        String dbUrl = "jdbc:mysql://localhost:3306/db_perpus";
        String dbUser = "root";
        String dbPass = "";

        String sql = "UPDATE pegawai SET nama=?, email=?, divisi=? WHERE nidn=?";

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection(dbUrl, dbUser, dbPass);

            if ("".equals(nidn.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "NIDN harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else if ("".equals(nama.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Nama harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else if ("".equals(email.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Email harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else if ("".equals(divisi.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Divisi harus diisi", "Error", JOptionPane.WARNING_MESSAGE);
            } else {
                try (PreparedStatement stmt = conn.prepareStatement(sql)) {

                    
                    stmt.setString(1, nama.getText());
                    stmt.setString(2, email.getText());
                    stmt.setString(3, divisi.getText());
                    stmt.setString(4, nidn.getText());

                    stmt.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
                    nidn.setText("");
                    nama.setText("");
                    email.setText("");
                    divisi.setText("");
                    showPanel();
                    loadData();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
                } finally {
                    conn.close();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), "Error! " + e.getMessage());
        }

    }

    private void hapusData() {
        int selectedRow = tabelpegawai.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang akan dihapus", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah yakin ingin menghapus data?",
                "Konfirmasi Hapus Data", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String idBuku = (String) tabelpegawai.getValueAt(selectedRow, 0);
            String dbUrl = "jdbc:mysql://localhost:3306/db_perpus";
            String dbUser = "root";
            String dbPass = "";

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection(dbUrl, dbUser, dbPass);
                String sql = "DELETE FROM pegawai WHERE nidn = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, idBuku);
                int rowsAffected = pst.executeUpdate();
                if (rowsAffected > 0) {
                    ((DefaultTableModel) tabelpegawai.getModel()).removeRow(selectedRow);
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data", "Error", JOptionPane.ERROR_MESSAGE);
                }
                pst.close();
                con.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void cariData() {
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MySQL://localhost:3306/db_perpus";
        SUser = "root";
        SPass = "";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();
            DefaultTableModel model = new DefaultTableModel(new String[]{"NIDN", "Nama Lengkap", "Email", "Divisi"}, 0);
            tabelpegawai.setModel(model);

            String searchKeyword = txtCari.getText();
            String sql = "SELECT * FROM pegawai WHERE nama LIKE '" + searchKeyword + "%'";
            java.sql.ResultSet rs = st.executeQuery(sql);

            String nidn, nama, email, divisi;
            while (rs.next()) {
                nidn = rs.getString("nidn");
                nama = rs.getString("nama");
                email = rs.getString("email");
                divisi = rs.getString("divisi");
                model.addRow(new Object[]{nidn, nama, email, divisi});
            }
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }

    }
    
}
